Repository anshjindal/api-core-backend, pull requests merged in 2025-03, with the labels that each got.

#36 Display Certificate Management Dashboard - 86a7h8guv
  models/certificate.js
  package-lock.json
  package.json
Labels: ems212

#37 Log Certificate Sending History - 86a7hahpg
  models/certificateHistory.js
Labels: ems212

#40 Database Structure (MongoDB) - Extended from EMS211 - 86a7hndj0
  models/teams.js
  models/users.js
  setup-remote.bat
  setup-remote.sh
Labels: ems212

#30 feat(teams): add team model and migration script (task_86a7h8vn0)
  config/db.js
  controllers/departmentController.js
  controllers/designationController.js
  controllers/employeeController.js
  controllers/leavesController.js
  controllers/loginController.js
  controllers/rolesController.js
  controllers/teamController.js
  h -v origin feat_ems_211_task_86a7h8vn0
  import-data.js
  index.js
  middlewares/authenticationMiddleware.js
  models/team.js
  package.json
  routes/authenticationRoutes.js
  routes/departmentRoutes.js
  routes/designationRoutes.js
  routes/employeeRoutes.js
  routes/leaves.js
  routes/roleRoutes.js
  routes/teamRoutes.js
  scripts/migrateTeams.js
  service/leavesService.js
  service/teamService.js
  utils/errorHandler.js
Labels: ems211

#39 feat(devops): set up jenkins pipeline for backend
  Jenkinsfile
  eslint.config.js
  package-lock.json
  package.json
Labels: ems211

#38 Feat EMS_209: 86a7gwx3e Load Real Data in Timesheet Table
  dummydata.js
  frontend/src/components/TimesheetTable.jsx
  index.js
  models/timesheetModel.js
  routes/timesheetRoutes.js
  service/timesheetService.js
  src/App.jsx
  src/components/TimesheetTable.jsx
  src/components/common/TimesheetTable.jsx
  utils/database.js
Labels: ems209

#44 Backend API for Bulk Certificate Generation - 86a7hahkf
  controllers/certificateController.js
  index.js
  models/certificate.js
  routes/certificateRoutes.js
  service/certificateService.js
Labels: ems212

#45 Feat 86a7hngrc: Refined Database Structure (MongoDB)
  models/timesheet.js
  models/users.js
  setup-remote.bat
  setup-remote.sh
Labels: ems211

#47 feat(auth): [Devops#3] Docker Integration & Image Management Backend
  $null
  .dockerignore
  .env.docker
  .env.local
  Dockerfile
  config/database.js
  import-data.js
  migrations/migrateEmployees.js
  migrations/migrateTeams.js
  package.json
  service/authenticationService.js
  utils/database.js
Labels: ems211

#48 Update CI/CD pipeline
  cicd/team_ems_208/Dockerfile.backend
  cicd/team_ems_208/Jenkinsfile
  cicd/team_ems_208/k3s/backend-deployment.yaml
  cicd/team_ems_208/k3s/backend-service.yaml
  eslint.config.mjs
  package-lock.json
  package.json
  setup-remote.bat
  setup-remote.sh
Labels: ems208

#51 Feat 86a7htrpj: Added Backend API for Email Notifications
  index.js
  package-lock.json
  routes/emailRoutes.js
  utils/emailService.js
Labels: ems302

#52 Feat 86a7htqh8: Add error handling for API call failures with user-friendly messages
  index.js
  middlewares/errorHandler.js
  routes/trainings.js
Labels: ems301

#61 Feat: document the feature(#86a7htrpm)
  README.md
Labels: ems302

#63 Feat 86a7htqh8: Implement DELETE training API with role-based access
  controllers/trainingsController.js
  index.js
  middlewares/authenticationMiddleware.js
  middlewares/authorizeRoles.js
  models/Training.js
  package-lock.json
  routes/trainings.js
  service/authenticationService.js
  utils/jwtUtility.js
Labels: ems301

#46 Docker Integration & Image Management
  Dockerfile
  Jenkinsfile
  k8s/ems-backend-deployment.yaml
  redisService.js
Labels: ems212

#56 (86a7gy1yj): add Error Handling for API Calls
  index.js
  middlewares/errorHandler.js
Labels: ems208

#62 Add Profile Picture Upload
  controllers/employeeController.js
  index.js
  package-lock.json
  routes/employeeRoutes.js
  uploads/EMPLOYEE00001.png
  utils/redisConfig.js
  utils/upload.js
Labels: ems208
