Repository anshjindal/api-core-backend, pull requests merged in 2025-04, with the labels that each got.

#68 Add Dummy data for interns
  index.js
  models/intern.js
  routes/internRoutes.js
Labels: ems208

#70 Feat 86a7h8u7x: Backend API for Document Upload
  controllers/teamController.js
  index.js
  middlewares/authenticationMiddleware.js
  models/team.js
  package-lock.json
  routes/teamRoutes.js
  scripts/migrateTeams.js
  service/teamService.js
  utils/errorHandler.js
Labels: ems211

#71 feat: delete offboarding process
  controllers/offboardingController.js
  routes/offboardingRoutes.js
Labels: ems302

#72 The backend of the task/milestone task
  index.js
  models/Task.js
  models/settings.js
  routes/settingRoutes.js
  routes/taskroutes.js
  setup-remote.bat
  setup-remote.sh
Labels: ems210

#67 Feat 86a7h8w0n: Migrate Existing Team Data to MongoDB
  models/users.js
  package-lock.json
  package.json
  scripts/teams.json
  scripts/teamsMigration.js
  scripts/users.json
Labels: ems211

#59 feat: add basic data setup for tests
  index.js
  tests/WOUESSITESTDATA/Wouessi.address.json
  tests/WOUESSITESTDATA/Wouessi.departments.json
  tests/WOUESSITESTDATA/Wouessi.designations.json
  tests/WOUESSITESTDATA/Wouessi.employees.json
  tests/WOUESSITESTDATA/Wouessi.roles.json
  tests/test-basic-DataSetup.js
Labels: ems211

#53 Add training routes
  dump.rdb
  index.js
  models/LeaveRequest.js
  package-lock.json
  package.json
  routes/leaveRequestRoutes.js
Labels: ems301

#24 feat(ui): ts migration
  commitlint.config.js
  commitlint.config.ts
  index.ts
  package-lock.json
  package.json
  seed/seed-blogs.js
  seed/seed-blogs.ts
  seed/seed-categories.js
  seed/seed-categories.ts
Labels: mpp

#76 Feat ems 302 - updated API response format
  controllers/employeeController.js
  helpers/employeeHelper.js
  index.js
  middlewares/authenticationMiddleware.js
  models/User.js
  models/address.js
  models/department.js
  models/employee.js
  routes/authenticationRoutes.js
  routes/departmentRoutes.js
  routes/designationRoutes.js
  routes/employee.js
  routes/employeeRoutes.js
  routes/offboardingRoutes.js
  routes/roleRoutes.js
  service/authenticationService.js
  service/employeeService.js
  utils/database.js
Labels: ems302

#78 Feat ems 302 fixed 60 86a7htrpc
  controllers/offboardingController.js
  middlewares/authenticationMiddleware.js
  models/OffboardingProcess.js
  package-lock.json
  package.json
  routes/employeeRoutes.js
  routes/leaves.js
  routes/offboardingRoutes.js
  routes/testToken.js
Labels: ems302
